### ISSUE TITLE
Update package to CUETools 2.2.2 (2022-06-02)

### ISSUE THREAD

**Issue by chuim** [wadoli/chocolatey-pkg-cuetools#1]
This new version is out since June but this package is still pointing to the previous one: http://cue.tools/wiki/CUETools_Changelog

**Comment by wadoli** [comment]
Thank you! 🙏

**Comment by wadoli** [comment]
I just submitted v2.2.2 for Moderation Review. You can check where the package is in the moderation queue here: https://ch0.co/moderation. Thanks again for the pull request, @chuim !

**Comment by chuim** [comment]
No problem. Thanks for pushing it through!
